sudo: false
dist: trusty

language: go

go: "1.14"

before_install:
- mkdir -p $HOME/supercronic
- rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/supercronic/
- export TRAVIS_BUILD_DIR=$HOME/supercronic
- cd $TRAVIS_BUILD_DIR
install:
- make deps
- git clone https://github.com/sstephenson/bats.git --branch v0.4.0 --depth 1 "${HOME}/bats"
- export "PATH=${PATH}:${HOME}/bats/bin"
jobs:
  include:
  - stage: test
    script:
    - make fmt
    - make test
  - stage: build
    script:
    - mkdir -p dist
    - export GOOS="linux"
    - export CGO_ENABLED=0
    - for arch in amd64 386 arm arm64; do GOARCH="$arch" go build && file supercronic
      | grep 'statically linked' && mv supercronic "dist/supercronic-${GOOS}-${arch}";
      done
    - pushd dist
    - ls -lah *
    - file *
    - sha1sum *
    - sha256sum *
    - popd
    deploy:
      provider: releases
      api_key:
        secure: "$GITHUB_OAUTH_TOKEN"
      file: dist/*
      file_glob: true
      skip_cleanup: true
      on:
        repo: vseinstrumentiru/supercronic
        branch: plain